version: "3.7"
services:
  symptom-diary-mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "symptomdiary"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "localuser"
      # You can use whatever password you like
      MYSQL_PASSWORD: "localpassword"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "localpassword"
    ports:
      - 3306:3306
    volumes:
      - symptom-diary-mysql:/var/lib/mysql
volumes:
  symptom-diary-mysql:
